// Note: having length != 4 will mess with layout based on how the site is styled
const bookmarks = [
  {
    title: "Daily",
    links: [
      { name: "Eric Ngigi", url: "https://ericngigi.com" },
      { name: "GitHub", url: "https://github.com/ErikNgigi" },
      { name: "Netlify", url: "https://app.netlify.com/teams/erikngigi/overview" },
      { name: "Website", url: "https://ericngigi.netlify.app" },
      { name: "Linkedin", url: "https://www.linkedin.com/in/eric-ngigi-073b72153/" },
      { name: "ChatGPT", url: "https://chat.openai.com/" },
      { name: "ALX", url: "https://member.theroom.com/alx/" },
      { name: "TOP", url: "https://www.theodinproject.com/dashboard" },
      { name: "HackerRank", url: "https://www.hackerrank.com/" },
      { name: "LeetCode", url: "https://leetcode.com/" },
      { name: "Indeed", url: "https://www.indeed.com/" },
      { name: "Fuzu", url: "https://www.fuzu.com/kenya" },
      { name: "OpenSource", url: "https://opensourcejobhub.com/" },
    ],
  },
  {
    title: "Media",
    links: [
      { name: "YouTube", url: "https://youtube.com" },
      { name: "Pahe", url: "https://pahe.li" },
      { name: "RARBG", url: "https://rarbgget.org/torrents.php"},
      { name: "Kitsu", url: "https://kitsu.io/explore/anime" },
      { name: "Nyaa", url: "https://nyaa.si/" },
      { name: "GogoAnime", url: "https://gogoanime.cl/" },
    ],
  },
  {
    title: "Arch Linux",
    links: [
      { name: "ArchWiki", url: "https://wiki.archlinux.org/" },
      { name: "Packages", url: "https://archlinux.org/packages/" },
      { name: "AUR", url: "https://aur.archlinux.org/" },
      { name: "News", url: "https://archlinux.org/" },
    ],
  },
  {
    title: "G-Suite",
    links: [
      { name: "Eric Wanyoike", url: "https://mail.google.com/mail/u/?authuser=ericwanyoike@gmail.com" },
      { name: "Docs", url: "https://docs.google.com/document/?usp=docs_alc&authuser=0" },
      { name: "Sheets", url: "https://docs.google.com/spreadsheets/?usp=sheets_alc&authuser=0" },
      { name: "Drive", url: "https://drive.google.com/?authuser=0" },
      { name: "Chats", url: "https://chat.google.com/?authuser=0" },
      { name: "Calender", url: "https://calendar.google.com/calendar?authuser=0" },
      { name: "Eric Ngigi", url: "https://mail.google.com/mail/u/?authuser=ericmosesngigi@gmail.com" },
      { name: "Docs", url: "https://docs.google.com/document/?usp=docs_alc&authuser=1" },
      { name: "Sheets", url: "https://docs.google.com/spreadsheets/?usp=sheets_alc&authuser=1" },
      { name: "Drive", url: "https://drive.google.com/?authuser=1" },
      { name: "Chats", url: "https://chat.google.com/?authuser=1" },
      { name: "Calender", url: "https://calendar.google.com/calendar?authuser=1" },
      { name: "ericwanyoike772", url: "https://mail.google.com/mail/u/?authuser=ericwanyoike772@gmail.com" },
      { name: "ericthegiggs", url: "https://mail.google.com/mail/u/?authuser=ericthegiggs@gmail.com" },
    ],
  },
  {
    title: "Sandbox Testing",
    links: [
      // { name: "Localhost:Crater", url: "http://localhost/" },
      // { name: "Localhost:8080", url: "http://localhost:8080" },
      { name: "PHPMyAdmin", url: "http://localhost:8080/phpmyadmin/" },
      { name: "Hugo", url: "http://localhost:1313" },
      { name: "Algoendeavours", url: "http://localhost:8080/algoendeavours/" },
    ],
  },
];
